In [1]:
import pandas as pd

In [3]:
hotel_df = pd.read_excel('hotel_bookings.xlsx')

In [6]:
hotel_df.head()

,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,...,deposit_type,agent,company,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date
0,Resort Hotel,0,342,2015,July,27,1,0,0,2,...,No Deposit,NaN,NaN,0,Transient,0.0,0,0,Check-Out,2015-07-01
1,Resort Hotel,0,737,2015,July,27,1,0,0,2,...,No Deposit,NaN,NaN,0,Transient,0.0,0,0,Check-Out,2015-07-01
2,Resort Hotel,0,7,2015,July,27,1,0,1,1,...,No Deposit,NaN,NaN,0,Transient,75.0,0,0,Check-Out,2015-07-02
3,Resort Hotel,0,13,2015,July,27,1,0,1,1,...,No Deposit,304.0,NaN,0,Transient,75.0,0,0,Check-Out,2015-07-02
4,Resort Hotel,0,14,2015,July,27,1,0,2,2,...,No Deposit,240.0,NaN,0,Transient,98.0,0,1,Check-Out,2015-07-03

In [5]:
hotel_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 119390 entries, 0 to 119389
Data columns (total 32 columns):
 #   Column                          Non-Null Count   Dtype
---  ------                          --------------   -----
 0   hotel                           119390 non-null  object
 1   is_canceled                     119390 non-null  int64
 2   lead_time                       119390 non-null  int64
 3   arrival_date_year               119390 non-null  int64
 4   arrival_date_month              119390 non-null  object
 5   arrival_date_week_number        119390 non-null  int64
 6   arrival_date_day_of_month       119390 non-null  int64
 7   stays_in_weekend_nights         119390 non-null  int64
 8   stays_in_week_nights            119390 non-null  int64
 9   adults                          119390 non-null  int64
 10  children                        119386 non-null  float64
 11  babies                          119390 non-null  int64
 12  meal                            119390 non-null  object
 13  country                         118902 non-null  object
 14  market_segment                  119390 non-null  object
 15  distribution_channel            119390 non-null  object
 16  is_repeated_guest               119390 non-null  int64
 17  previous_cancellations          119390 non-null  int64
 18  previous_bookings_not_canceled  119390 non-null  int64
 19  reserved_room_type              119390 non-null  object
 20  assigned_room_type              119390 non-null  object
 21  booking_changes                 119390 non-null  int64
 22  deposit_type                    119390 non-null  object
 23  agent                           103050 non-null  float64
 24  company                         6797 non-null    float64
 25  days_in_waiting_list            119390 non-null  int64
 26  customer_type                   119390 non-null  object
 27  adr                             119390 non-null  float64
 28  required_car_parking_spaces     119390 non-null  int64
 29  total_of_special_requests       119390 non-null  int64
 30  reservation_status              119390 non-null  object
 31  reservation_status_date         119390 non-null  datetime64[ns]
dtypes: datetime64[ns](1), float64(4), int64(16), object(11)
memory usage: 29.1+ MB

In [7]:
# 결측치 확인 - children, country, agent, company 결측치 존재.
hotel_df.isnull().sum()

hotel                                  0
is_canceled                            0
lead_time                              0
arrival_date_year                      0
arrival_date_month                     0
arrival_date_week_number               0
arrival_date_day_of_month              0
stays_in_weekend_nights                0
stays_in_week_nights                   0
adults                                 0
children                               4
babies                                 0
meal                                   0
country                              488
market_segment                         0
distribution_channel                   0
is_repeated_guest                      0
previous_cancellations                 0
previous_bookings_not_canceled         0
reserved_room_type                     0
assigned_room_type                     0
booking_changes                        0
deposit_type                           0
agent                              16340
company                           112593
days_in_waiting_list                   0
customer_type                          0
adr                                    0
required_car_parking_spaces            0
total_of_special_requests              0
reservation_status                     0
reservation_status_date                0
dtype: int64

In [22]:
# 특성 삭제 - arrival_date_week_number, hotel, distribution_channel, company데이터 셋 삭제.
hotel_df = hotel_df.drop(['arrival_date_week_number', 'hotel', 'distribution_channel', 'company'], axis = 1)

In [20]:
# 특성 대치 - children, agent, country
hotel_df['children'] = hotel_df['children'].fillna(0)
hotel_df['agent'] = hotel_df['agent'].fillna(-1)
hotel_df['country'] = hotel_df['country'].fillna('undefined')

In [26]:
# 결측치 제거 완료.
hotel_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 119390 entries, 0 to 119389
Data columns (total 28 columns):
 #   Column                          Non-Null Count   Dtype
---  ------                          --------------   -----
 0   is_canceled                     119390 non-null  int64
 1   lead_time                       119390 non-null  int64
 2   arrival_date_year               119390 non-null  int64
 3   arrival_date_month              119390 non-null  object
 4   arrival_date_day_of_month       119390 non-null  int64
 5   stays_in_weekend_nights         119390 non-null  int64
 6   stays_in_week_nights            119390 non-null  int64
 7   adults                          119390 non-null  int64
 8   children                        119390 non-null  float64
 9   babies                          119390 non-null  int64
 10  meal                            119390 non-null  object
 11  country                         119390 non-null  object
 12  market_segment                  119390 non-null  object
 13  is_repeated_guest               119390 non-null  int64
 14  previous_cancellations          119390 non-null  int64
 15  previous_bookings_not_canceled  119390 non-null  int64
 16  reserved_room_type              119390 non-null  object
 17  assigned_room_type              119390 non-null  object
 18  booking_changes                 119390 non-null  int64
 19  deposit_type                    119390 non-null  object
 20  agent                           119390 non-null  float64
 21  days_in_waiting_list            119390 non-null  int64
 22  customer_type                   119390 non-null  object
 23  adr                             119390 non-null  float64
 24  required_car_parking_spaces     119390 non-null  int64
 25  total_of_special_requests       119390 non-null  int64
 26  reservation_status              119390 non-null  object
 27  reservation_status_date         119390 non-null  datetime64[ns]
dtypes: datetime64[ns](1), float64(3), int64(15), object(9)
memory usage: 25.5+ MB

In [27]:
hotel_df['']

KeyError: ''

In [ ]:
# https://www.kaggle.com/atasaygin/hotel-booking-demand-eda-and-of-guest-prediction#Data-Cleaning
# https://www.kaggle.com/duygut/eda-booking-cancelation-prediction#2.-Dealing-with-Missing-Data-and-Correlation-Matrix